### ISSUE TITLE
Figure out why master is failing on Travis

### ISSUE THREAD

**Issue by striglia** [striglia/pyramid_swagger#111]
Worked locally, and the change is not interesting enough to be responsible. It's passed previously, so I'm suspecting something has changed out from under us. Possibly on the Travis side?

SSV merge worked: https://travis-ci.org/striglia/pyramid_swagger/builds/60266076
1.5.0 on py3x failed: https://travis-ci.org/striglia/pyramid_swagger/builds/62315510
Rebuild failed: https://travis-ci.org/striglia/pyramid_swagger/builds/62315520

Roughly a 15 day gap between the clean and failing builds...

**Comment by prat0318** [comment]
This is weird. Travis shows codec issue at the [line](https://github.com/striglia/pyramid_swagger/blob/master/setup.py#L13) which reads from `README.rst` but it has not been changed in this commit. I would try a build again today as it could be a Travis issue.

**Comment by striglia** [comment]
Just rebuilt the previously-green [SSV merge](https://travis-ci.org/striglia/pyramid_swagger/builds/60266076) and it broke in the same way. I'm calling this as a Travis change in the intervening time. Googled around a bit and couldn't identify what's up. 

Seems suspicious that we're doing a py3x test using a py2x interpreter, but I'm not sure whether that's changed recently.

https://travis-ci.org/striglia/pyramid_swagger/jobs/60266079#L299

**Comment by prat0318** [comment]
It is because Travis is now using `tox` version `2.0.0` instead of earlier `1.9.2`.

On my local:
```
(mypy)dev32-devc➜ pyramid_swagger:(master)U  /nail/home/agarwal/mypy/bin/tox --version            [12:29:15]
2.0.0 imported from /nail/home/agarwal/mypy/lib/python2.6/site-packages/tox/__init__.pyc
(mypy)dev32-devc➜ pyramid_swagger:(master)U  /nail/home/agarwal/mypy/bin/tox -e py33              [12:29:24]
GLOB sdist-make: /nail/home/agarwal/srv/pyramid_swagger/setup.py
py33 create: /nail/home/agarwal/srv/pyramid_swagger/.tox/py33
py33 installdeps: coverage, mock, pytest, webtest
py33 inst: /nail/home/agarwal/srv/pyramid_swagger/.tox/dist/pyramid_swagger-1.5.0.zip
ERROR: invocation failed (exit code 1), logfile: /nail/home/agarwal/srv/pyramid_swagger/.tox/py33/log/py33-2.log
ERROR: actionid: py33
msg: installpkg
cmdargs: [local('/nail/home/agarwal/srv/pyramid_swagger/.tox/py33/bin/pip'), 'install', '/nail/home/agarwal/srv/pyramid_swagger/.tox/dist/pyramid_swagger-1.5.0.zip']
env: {'PATH': '/nail/home/agarwal/srv/pyramid_swagger/.tox/py33/bin:/nail/home/agarwal/mypy/bin:/nail/home/agarwal/.vim74/bin:/nail/home/agarwal/bin/cmake/bin:./bin:/nail/home/agarwal/.rbenv/shims:/usr/local/bin:/usr/local/sbin:/nail/home/agarwal/.sfs:/nail/home/agarwal/.dotfiles/bin:/nail/sys/bin:/nail/workflow:/nail/scripts:/opt/rbenv/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin', 'VIRTUAL_ENV': '/nail/home/agarwal/srv/pyramid_swagger/.tox/py33', 'PYTHONHASHSEED': '142389557', 'TMPDIR': '/nail/tmp'}

Processing ./.tox/dist/pyramid_swagger-1.5.0.zip
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/nail/tmp/pip-eymsht-build/setup.py", line 13, in <module>
        long_description = f.read()
      File "/nail/home/agarwal/srv/pyramid_swagger/.tox/py33/lib/python3.3/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 860: ordinal not in range(128)

    ----------------------------------------
    Command "python setup.py egg_info" failed with error code 1 in /nail/tmp/pip-eymsht-build

py33 installed: Babel==0.9.4,beautifulsoup4==4.3.2,ClientCookie==1.3.0,coverage==3.7.1,flufl.enum==3.3.2,lxml==2.2.4,mock==1.0.1,mod-python==3.3.1,oauth2===1.2.1-yelp3,pbkdf2==1.3,pexpect==2.3,py==1.4.27,pycrypto==2.0.1,pyExcelerator==0.6.4.1,pykss==0.4,-e git+git@github.com:prat0318/pyramid_swagger.git@36e856e6f4307623e167758e65ac2a96d194e695#egg=pyramid_swagger-master,pysqlite==2.5.5,pysubnettree==0.12,pytest==2.7.0,pytz==2011rc0,PyYAML==3.9,rpy==1.0.3,scipy==0.8.0,setproctitle==1.0,six==1.9.0,Twisted-Conch==10.0.0,Twisted-Lore==10.0.0,Twisted-Mail==10.0.0,Twisted-Names==10.0.0,Twisted-News==10.0.0,Twisted-Web==10.0.0,Twisted-Words==10.0.0,waitress==0.8.9,WebOb==1.4.1,WebTest==2.0.18
__________________________________________________ summary __________________________________________________
ERROR:   py33: InvocationError: /nail/home/agarwal/srv/pyramid_swagger/.tox/py33/bin/pip install /nail/home/agarwal/srv/pyramid_swagger/.tox/dist/pyramid_swagger-1.5.0.zip (see /nail/home/agarwal/srv/pyramid_swagger/.tox/py33/log/py33-2.log)
```
