### ISSUE TITLE
500 HTTP error being thrown when missing required request parameter

### ISSUE THREAD

**Issue by mikeecb** [striglia/pyramid_swagger#168]
Posting a request with a missing parameter that is `required: True` in `swagger.yaml` does not throw a `400` error but instead throws a `500` error. This seems to be the case for `GET` parameters and `POST` body (but not the body properties, which acts as expected).

Here's a test `POST` endpoint:
```
    /test:
        post:
            description: Test endpoint
            parameters:
            -   in: body
                name: body
                required: True
                schema:
                    properties:
                        my_property:
                            description: Test property
                            type: integer
                    required:
                    - my_property
                    type: object
            responses:
                '200':
                    description: An uploaded resource, including S3 URL.
            tags:
            - swagger
```

Sending a `POST` request with all the required parameters acts as expected and returns:
```
POST /test HTTP/1.1
Host: ****
Content-Type: application/json
Cache-Control: no-cache

{
    "my_property": 1  
}
```

Sending a `POST` request with the required property, `my_property`, missing correctly throws a `400` error. Request:
```
POST /test HTTP/1.1
Host: ****
Content-Type: application/json
Cache-Control: no-cache

{}
```
Response:
```
<html>
 <head>
  <title>400 Bad Request</title>
 </head>
 <body>
  <h1>400 Bad Request</h1>
  The server could not comply with the request since it is either malformed or otherwise incorrect.<br/><br/>
'my_property' is a required property

Failed validating 'required' in schema:
    {'properties': {'my_property': {'description': 'Test property',
                                    'type': 'integer'}},
     'required': ['my_property'],
     'type': 'object'}

On instance:
    {}


 </body>
</html>
```

**However**, not sending a body at all incorrectly throws a `500` error. This doesn't even hit the view endpoint.
```
POST /test HTTP/1.1
Host: ****
Content-Type: application/json
Cache-Control: no-cache
```
Response:
```
<html>
 <head>
  <title>500 Internal Server Error</title>
 </head>
 <body>
  <h1>500 Internal Server Error</h1>
  The server has either erred or is incapable of performing the requested operation.<br/><br/>
 </body>
</html>
```

Running `pip freeze | grep bravado` gives `bravado-core==4.2.2`. Also running `pip freeze | grep swagger` gives:
```
pyramid-swagger==2.3.0-rc2
swagger-spec-validator==2.0.2\
```
This is also an issue with `GET` required query parameters.

**Comment by mejymejy** [comment]
I ran into this today and was able to get a traceback:
```python
Traceback (most recent call last):
  File "/virtualenv_run/lib/python3.6/site-packages/bravado_core/param.py", line 181, in unmarshal_param
    raw_value = request.json()
  File "/virtualenv_run/lib/python3.6/site-packages/pyramid_swagger/tween.py", line 263, in json
    return getattr(self.request, 'json_body', {})
  File "/virtualenv_run/lib/python3.6/site-packages/pyramid/request.py", line 237, in json_body
    return json.loads(text_(self.body, self.charset))
  File "/usr/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/virtualenv_run/lib/python3.6/site-packages/pyramid_swagger/tween.py", line 464, in _validate
    return f(*args, **kwargs)
  File "/virtualenv_run/lib/python3.6/site-packages/pyramid_swagger/tween.py", line 572, in swaggerize_request
    request_data = unmarshal_request(request, op)
  File "/virtualenv_run/lib/python3.6/site-packages/bravado_core/request.py", line 66, in unmarshal_request
    param_value = unmarshal_param(param, request)
  File "/virtualenv_run/lib/python3.6/site-packages/bravado_core/param.py", line 184, in unmarshal_param
    format(str(json_error)))
bravado_core.exception.SwaggerMappingError: Error reading request body JSON: Expecting value: line 1 column 1 (char 0)
```
