### ISSUE TITLE
"File" paramType causes validation to fail

### ISSUE THREAD

**Issue by johnschultz** [striglia/pyramid_swagger#99]
Looks like fixing form validation exposed a bug with parameters of type `File`. This is what happens when I run a test that uses webtest's upload_files arg (http://webtest.readthedocs.org/en/latest/testapp.html#making-requests) with a `File` type argument in swagger.
### Swagger:

``` JSON
        {
            "path": "/business/{business_id}/media/photo/v1",
            "operations": [
                {
                    "summary": "Upload a business photo",
                    "notes": "<a href='mock_responses/media_examples/business_{business_id}_media_photo_v1_response.POST.json'>Example response</a>",
                    "method": "POST",
                    "nickname": "createPhoto",
                    "parameters": [
                        {
                            "name": "business_id",
                            "type": "string",
                            "description": "Business identifier",
                            "required": true,
                            "paramType": "path"
                        },
                        {
                            "name": "photo",
                            "type": "File",
                            "description": "Binary photo data",
                            "required": true,
                            "paramType": "form"
                        },
                        {
                            "name": "caption",
                            "type": "string",
                            "description": "Photo caption",
                            "required": false,
                            "paramType": "form"
                        }
                    ],
                    "type": "BusinessPhotoResponse",
                    "consumes": ["multipart/form-data"]
                }
            ]
        },
```
### Failure:

``` python
tests/integration_tests/api/business/media_integration_test.py ...Traceback (most recent call last):
  File "/nail/home/jschultz/pg/biz_app/.tox/py/local/lib/python2.7/site-packages/pyramid/tweens.py", line 21, in excview_tween
    response = handler(request)
  File "/nail/home/jschultz/pg/biz_app/.tox/py/local/lib/python2.7/site-packages/pyramid_swagger/tween.py", line 114, in validator_tween
    validator_map)
  File "/nail/home/jschultz/pg/biz_app/.tox/py/local/lib/python2.7/site-packages/pyramid_swagger/tween.py", line 204, in handle_request
    validate_request(validation_pairs)
  File "/nail/home/jschultz/pg/biz_app/.tox/py/local/lib/python2.7/site-packages/pyramid_swagger/tween.py", line 286, in _validate
    raise exc_class(str(exc))
RequestValidationError: 'photo' is a required property

Failed validating 'required' in schema[u'properties']['photo']:
    {u'additionalProperties': False,
     u'properties': {'caption': {'description': 'Photo caption',
                                 'name': 'caption',
                                 'paramType': 'form',
                                 'required': False,
                                 'type': 'string'},
                     'photo': {'description': 'Binary photo data',
                               'name': 'photo',
                               'paramType': 'form',
                               'required': True,
                               'type': 'File'}},
     u'type': u'object'}

On instance['photo']:
    {}
```

**Comment by dnephin** [comment]
By exposed, you mean introduced, right?  I'm pretty sure this is the new validation failing on the service call because it can't find the field `photo` in the form data, because it's not in the form data. It's available from a different request field.  

We just have to account for that, probably by adding the field in the return value of `SwaggerPyramidRequest.form`, I think.

**Comment by dnephin** [comment]
Actually, I think I'm a bit off. It's not that the data is on a different field, it's that jsonschema expects a dict at that value, but the param is an object of some type.

**Comment by striglia** [comment]
Looks like you'll want to extend all Validators that could ever encounter a File object to actually support validation on them. I'm under the impression that both the HTTP and Swagger1.2 specs only support them in form-encoded bodies. If that's the case, you can just change the form validator to some extended version of the `Swagger12ParamValidator` it currently uses and make that extended validator support File objects.

That said, once we get 2.0 support and delegate all validation to bravado-core, this feature needs to be supported there not in pyramid_swagger. Up to you whether doing this work is worth it, and I'd suggest making sure bravado-core supports the same feature too.

**Comment by analogue** [comment]
I think this is the same as #113. I'll get to the bottom of it tomorrow.
